export const NAV_ITEMS = [
  { id: 'overview', label: 'Overview', path: '/', icon: 'LayoutDashboard' },
  { id: 'live-network', label: 'Live Network', path: '/live-network', icon: 'Activity' },
  { id: 'forecast', label: 'Attack Forecast', path: '/forecast', icon: 'TrendingUp' },
  { id: 'network-graph', label: 'Network Graph', path: '/network-graph', icon: 'Network' },
  { id: 'disagreements', label: 'Disagreements', path: '/disagreements', icon: 'GitCompare' },
  { id: 'incidents', label: 'Incidents', path: '/incidents', icon: 'ShieldAlert' },
  { id: 'explainability', label: 'Explainability', path: '/explainability', icon: 'Sparkles' },
];

export const MITRE_TACTICS = [
  'Initial Access',
  'Execution',
  'Persistence',
  'Privilege Escalation',
  'Defense Evasion',
  'Credential Access',
  'Discovery',
  'Lateral Movement',
  'Collection',
  'Command and Control',
  'Exfiltration',
  'Impact',
];

export const SCENARIOS = [
  {
    id: 'default',
    name: 'Standard Baseline Scenario',
    severity: 'High',
    badge: 'Baseline',
    color: 'border-[#ded0bc] hover:border-[#b45309]',
    shortSummary: 'Privilege escalation on SecOps floor workstation; T+1 forecast predicts lateral propagation to Domain Controller.',
    whatIsIt: 'A standard compromised workstation scenario where an attacker obtains elevated local privileges on Endpoint-07.',
    whatWillHappen: 'The simulation activates token impersonation on Endpoint-07. The attacker elevates user permissions and begins staging cross-subnet probes.',
    whatThreatCastShows: 'ThreatCast AI detects the anomalous token elevation and forecasts a K=3 trajectory: Lateral Movement to Server-03 within 12 minutes, followed by Credential Dumping, culminating in Data Exfiltration.',
    whyItMatters: 'Unchecked privilege escalation is the precursor to domain takeover. Catching the attack before lateral propagation prevents enterprise-wide compromise.',
    whatItDemonstrates: 'ThreatCast\'s ability to identify early-stage attack progression and anticipate multi-step lateral movement using FastRP graph embeddings.',
    technicalDetails: {
      initialTactic: 'TA0004 - Privilege Escalation (T1134.001 Token Impersonation)',
      sourceEndpoint: 'Endpoint-07 (10.0.2.7) / User-014 (SecOps)',
      targetEndpoint: 'Server-03 (10.0.3.3)',
      predictedHops: 'Endpoint-07 -> Server-03 -> Database-02 -> Gateway-01',
      modelUsed: 'LSTM-B with FastRP 128-dim embeddings',
    },
    preSimulationSteps: [
      'Simulate token elevation on Endpoint-07 workstation',
      'Observe anomalous RPC handles to Domain Controller Server-03',
      'Update temporal network graph topology',
      'Compute K=3 future attack progression states (T+1, T+2, T+3)',
      'Generate automated proactive defensive playbooks',
    ],
    recommendedActions: [
      { action: 'Isolate Endpoint-07 host network adapter immediately', why: 'Prevents the adversary from using this machine as a pivot point for lateral movement.' },
      { action: 'Revoke active Kerberos TGT ticket for User-014', why: 'Invalidates compromised authentication tokens before domain services accept them.' },
      { action: 'Block port 445 SMB routing between SecOps floor and Infrastructure subnets', why: 'Restricts RPC/SMB traversal vectors to the Domain Controller.' },
    ],
  },
  {
    id: 'lateral_movement_wave',
    name: 'Active Lateral Movement Wave',
    severity: 'Critical',
    badge: 'Critical Wave',
    color: 'border-[#fdba74] hover:border-[#ea580c]',
    shortSummary: 'Compromised endpoint aggressively traversing domain controller via SMB/RPC admin shares.',
    whatIsIt: 'An active propagation scenario where an adversary uses valid stolen credentials to move laterally across subnet boundaries.',
    whatWillHappen: 'Workstation Endpoint-07 mounts administrative shares (C$) on Server-03 and attempts PsExec remote process spawning.',
    whatThreatCastShows: 'ThreatCast AI identifies active lateral movement and forecasts imminent LSASS credential dumping on Server-03 (93% confidence in 8 minutes), followed by customer database staging.',
    whyItMatters: 'Lateral movement allows an attacker to spread from an isolated workstation into core domain infrastructure and high-value databases.',
    whatItDemonstrates: 'ThreatCast\'s graph-aware neural network recognizing cross-subnet topological traversal in real time.',
    technicalDetails: {
      initialTactic: 'TA0008 - Lateral Movement (T1021.002 SMB/Admin Shares)',
      sourceEndpoint: 'Endpoint-07 (10.0.2.7)',
      targetEndpoint: 'Server-03 (10.0.3.3) -> Database-02 (10.0.4.2)',
      predictedHops: 'Endpoint-07 -> Server-03 (DC) -> Database-02 (DB) -> Gateway-01',
      modelUsed: 'LSTM-B (Graph FastRP Temporal Model)',
    },
    preSimulationSteps: [
      'Inject active SMB/RPC cross-subnet connection events from Endpoint-07',
      'Trigger administrative share mounting on Server-03',
      'Recalculate node risk centrality and graph traversal probabilities',
      'Forecast T+1 LSASS dumping (8 min) and T+2 Database staging (18 min)',
      'Highlight critical disagreement with legacy static firewall rules',
    ],
    recommendedActions: [
      { action: 'Quarantine Endpoint-07 & Server-03 immediately', why: 'Halts ongoing active session propagation between workstation and server.' },
      { action: 'Enable Credential Guard on Server-03 and rotate krbtgt account', why: 'Protects LSASS memory from being dumped by elevated processes.' },
      { action: 'Enable micro-segmentation on Database Subnet 10.0.4.0/24', why: 'Blocks unauthorized database access even if Server-03 is partially compromised.' },
    ],
  },
  {
    id: 'exfiltration_crisis',
    name: 'Imminent Data Exfiltration Crisis',
    severity: 'Emergency',
    badge: 'Emergency',
    color: 'border-[#fca5a5] hover:border-[#dc2626]',
    shortSummary: '12.4 GB customer DB archive staged; K=3 forecast predicts external egress in <4 minutes.',
    whatIsIt: 'A high-urgency data theft scenario where customer financial and personal data has been staged and compressed for egress.',
    whatWillHappen: '12.4 GB of customer financial records on Database-02 are compressed into hidden directory /var/tmp/.staging, with outbound TLS sockets opened to Gateway-01.',
    whatThreatCastShows: 'ThreatCast AI detects data collection & compression and warns that external TLS egress to an unauthorized public IP is imminent within 4 minutes (96% confidence).',
    whyItMatters: 'Data exfiltration results in severe regulatory penalties, data privacy breaches, and corporate extortion if not blocked before bytes leave the perimeter.',
    whatItDemonstrates: 'ThreatCast\'s rapid predictive early warning that gives defenders a crucial 4-minute intervention window before exfiltration completes.',
    technicalDetails: {
      initialTactic: 'TA0009 - Collection (T1560.001 Archive via Utility / 12.4 GB Staged)',
      sourceEndpoint: 'Database-02 (10.0.4.2)',
      targetEndpoint: 'Gateway-01 (10.0.0.1) -> External C2 IP (198.51.100.42)',
      predictedHops: 'Database-02 -> Gateway-01 -> Public C2 Destination',
      modelUsed: 'LSTM-B Temporal Exfiltration Velocity Estimator',
    },
    preSimulationSteps: [
      'Simulate 12.4 GB database dump and compression into hidden staging directory',
      'Observe anomalous high-volume outbound socket requests to Gateway-01',
      'Trigger Emergency Early Warning countdown (< 4 minutes to impact)',
      'Forecast T+1 TLS Egress, T+2 Log Shredding, T+3 Extortion Deployment',
      'Generate immediate perimeter egress block rules',
    ],
    recommendedActions: [
      { action: 'Block Gateway-01 outbound egress traffic to IP 198.51.100.42', why: 'Physically cuts off the adversary\'s external command-and-control connection.' },
      { action: 'Freeze read/write IO on Database-02 customer tables volume', why: 'Prevents additional data extraction and prevents deletion of original records.' },
      { action: 'Rotate Database master credentials & terminate active query sessions', why: 'Evicts the attacker\'s compromised connection handle from the database engine.' },
    ],
  },
  {
    id: 'ransomware_staging',
    name: 'Ransomware Staging & Anti-Forensics',
    severity: 'Critical',
    badge: 'High Impact',
    color: 'border-[#d8b4fe] hover:border-[#9333ea]',
    shortSummary: 'Shadow copy destruction and mass encryption staging across critical server cluster.',
    whatIsIt: 'A destructive ransomware scenario where an adversary disables backups, clears security event logs, and stages cryptographic encryption binaries.',
    whatWillHappen: 'The adversary executes vssadmin delete shadows on Server-03, clears Windows security event logs, and stages encryption payloads on shared disks.',
    whatThreatCastShows: 'ThreatCast AI detects defense evasion and log clearing, forecasting mass encryption and extortion note deployment within 5 minutes (92% confidence).',
    whyItMatters: 'Ransomware causes complete operational shutdown and catastrophic business disruption if shadow copies and backups are destroyed.',
    whatItDemonstrates: 'ThreatCast\'s early warning identifying anti-forensic indicators before the encryption loop is executed.',
    technicalDetails: {
      initialTactic: 'TA0005 - Defense Evasion (T1070 Log Clearing & Shadow Copy Erasure)',
      sourceEndpoint: 'Server-03 (10.0.3.3) & Endpoint-07 (10.0.2.7)',
      targetEndpoint: 'Database-02 (10.0.4.2) / Workstation Pool',
      predictedHops: 'Server-03 -> Mass Workstation Spread -> Database Storage Encryption',
      modelUsed: 'LSTM-B Defense Evasion & Impact Trajectory Model',
    },
    preSimulationSteps: [
      'Simulate vssadmin shadow copy deletion on Server-03',
      'Observe rapid event log clearing (wevtutil cl Security)',
      'Detect encryption binary staging across shared network folders',
      'Forecast T+1 Mass Encryption, T+2 Workstation Locking, T+3 Ransom Notes',
      'Trigger emergency immutable snapshot and isolation playbooks',
    ],
    recommendedActions: [
      { action: 'Trigger emergency immutable snapshot of Database-02 & Server-03', why: 'Guarantees an uncorrupted, tamper-proof recovery point before encryption can execute.' },
      { action: 'Terminate PsExec and WMI remote execution permissions across workstation pool', why: 'Prevents the ransomware spreader script from launching payloads on peer machines.' },
      { action: 'Lock SIEM syslog ingestion forwarding to preserve audit logs out-of-band', why: 'Ensures forensic evidence is preserved even if local host logs are cleared.' },
    ],
  },
];
